### PR TITLE
Add python markdown div example

### PR DESCRIPTION
**Pull request by learn-more**
Edited in the `external/imgui_md/imgui_md_wrapper/imgui_md_wrapper.h` file,
updated with `py external\imgui_md\bindings\generate_imgui_md.py`

### CODE REVIEW

**Comment by pthom** [comment]
Thanks a lot, this is perfect, with the addition of having run the generator which is even more perfect. Thanks!

**Comment by learn-more** [comment]
> Thanks a lot, this is perfect, with the addition of having run the generator which is even more perfect. Thanks!

Thanks!

I had to apply a small patch on the generator for it to work on Windows (without destroying the line endings),
there is a PR for that as well.

**Comment by pthom** [comment]
Your contributions are first class! Do not hesitate to post more, if you so wish. I'm very opened to contributions like yours.

**Comment by learn-more** [comment]
> Your contributions are first class! Do not hesitate to post more, if you so wish. I'm very opened to contributions like yours.

Thank you!

I am in the process of experimenting with this bundle from c++ and python,
and considering how active you are, I will send in new patches when I encounter issues.

**Pull request merged**
