### PR TITLE
Use bundled imgui for hello_imgui sources

### PR DESCRIPTION
**Pull request by hmaarrfk**
its unclear to me why you would want to use two different sources?

Its hard enough to keep things consistent, getting rid of one source tree would help... i think.

### CODE REVIEW

**Comment by pthom** [comment]
See the commits on top the imgui_bundle branch of my imgui fork:

https://github.com/pthom/imgui/commits/imgui_bundle/

Those are patches which I regularly rebase on top of the latest imgui docking release:
* Most of them are related to python bindings (one cannot use bare function pointers, and using std::string vs char* if often better)
* Some others are "comfort" additions (horizontal layout utilities by thedmd)
* Other provide access to [ImGui Manual](https://pthom.github.io/imgui_manual_online/manual/imgui_manual.html) for python users. By the way, I authored this manual several years ago, and it does also provide code examples for python users
image

**Comment by hmaarrfk** [comment]
does it really load blazingly fast? .... that a little insane.

**Comment by pthom** [comment]
This is pure emscripten, not pyodide. And yes, it is fast :-)

**Comment by hmaarrfk** [comment]
its a little refreshing to see the use of 120Hz can actually be obtained....

**Pull request closed without merging**
