### PR TITLE
imgui_bundle.imgui: improve font_atlas_get_tex_data_as_rgba32

### PR DESCRIPTION
**Pull request by dcnieho**
remove `font_atlas_get_tex_data_as_rgba32` free function and make `get_tex_data_as_rgba32` member of `FontAtlas`.

Since it is manually declared anyway, its easily done like this so that the function is found where it is expected.

### CODE REVIEW

**Comment by pthom** [comment]
Thanks!

I had thought of that. However the stub file should also be updated so that code completion works.

The stub is also autogenerated, and there is an issue [here](https://github.com/pthom/imgui_bundle/blob/308ba4f73a484aefc3c5424b90b2a21d72d1aaeb/bindings/imgui_bundle/imgui/__init__.pyi#L6358) : it is possible to add a method after the fact in the C++ bindings, however I did not find a way to do it in the stub file.

**Comment by dcnieho** [comment]
Hmm, it would be legal to later extend a class with more class methods. See [here](https://stackoverflow.com/a/2982/3103767).

So we could insert some manual code to a the bottom of the stub file mirroring the pybind file:
```
ImFontAtlas.get_tex_data_as_rgba32 = font_atlas_get_tex_data_as_rgba32
```
Whether the corrects docs are then shown (which need to manually be copied into `font_atlas_get_tex_data_as_rgba32`, which currently also doesn't have the right docs) i do not know, but at least the stub should be fine that way.

Shall i add that to the PR?

**Comment by pthom** [comment]
> So we could insert some manual code to a the bottom of the stub file mirroring the pybind file:
> 
> ```
> ImFontAtlas.get_tex_data_as_rgba32 = font_atlas_get_tex_data_as_rgba32
> ```

Could you test if that gives a correct autocomplete? If possible, can you also check if mypy is happy with it?

**Comment by dcnieho** [comment]
I will check autocomplete, but i have no idea what mypy even is :p

**Pull request closed without merging**
