### PR TITLE
fix to add_colormap, uses np.array[uint32]

### PR DESCRIPTION
**Pull request by nick-0**
Amended add_colormap to take a numpy array of type uint32.

I was having trouble where implot.plot_heatmap was really eating at my CPU.  Reading into it, the issue has been resolved (see the implot backend branch), but I wanted to take it even further by only rendering the plot when needed.  To do that I needed my colorbar to match exactly.

Here is an example usage using a Matplotlib colormap and implot.plot_image:

```python
from imgui_bundle import imgui, immapp, implot
from OpenGL import GL
import matplotlib as mpl
import numpy as np

image_dirty = True
tex_id = None
cmap_name = 'turbo'
vmin=-0.2
vmax=1.0

def gui():
    global image_dirty
    global tex_id
    global cmap
    imgui.text("Hello, image heatmap!")

    if image_dirty:
        x = np.linspace(-4,4, 401)
        xx = np.outer(x,x)
        yy = np.sinc(xx)
        scalar_mappable = mpl.cm.ScalarMappable(None,cmap_name)
        scalar_mappable.set_clim(vmin,vmax)
        img_np = scalar_mappable.to_rgba(yy,bytes=True)
        
        tex_id = GL.glGenTextures(1)
        GL.glBindTexture(GL.GL_TEXTURE_2D, tex_id)
        GL.glTextureParameteri(tex_id, GL.GL_TEXTURE_MIN_FILTER, GL.GL_LINEAR)
        GL.glTextureParameteri(tex_id, GL.GL_TEXTURE_MAG_FILTER, GL.GL_LINEAR)
        GL.glTextureParameteri(tex_id, GL.GL_TEXTURE_WRAP_S, GL.GL_CLAMP_TO_BORDER)
        GL.glTextureParameteri(tex_id,GL.GL_TEXTURE_WRAP_T, GL.GL_CLAMP_TO_BORDER)
        GL.glTexImage2D(GL.GL_TEXTURE_2D, 0, GL.GL_RGBA, img_np.shape[0], img_np.shape[1],0,
                        GL.GL_RGBA, GL.GL_UNSIGNED_BYTE,img_np)
        image_dirty = False

    axis_flags = implot.AxisFlags_.no_initial_fit | implot.AxisFlags_.foreground #implot.AxisFlags_.lock | implot.AxisFlags_.no_grid_lines | implot.AxisFlags_.no_tick_marks

    implot.set_next_axes_limits(-4,4,-4,4)
    if implot.begin_plot("Sinc Function",[imgui.get_content_region_avail().x*.85,-1],implot.Flags_.no_legend | implot.Flags_.no_mouse_text):
        implot.setup_axes(None,None, axis_flags, axis_flags)
        implot.plot_image("##img_plot",tex_id, [-4,-4],[4,4])
        implot.end_plot()

    imgui.same_line()

    if implot.get_colormap_index(cmap_name) ==-1:
        colors= mpl.colors.to_rgba_array(mpl.colormaps[cmap_name].colors)*255
        colors_u32 = np.concatenate(colors.astype('uint8')).view('uint32')
        cmap = implot.add_colormap(cmap_name,colors_u32,len(colors_u32))

    implot.colormap_scale("##heatmap_scale",  vmin, vmax,imgui.ImVec2(-1,-1),"%g",0,cmap)

immapp.run(
    gui_function=gui,  # The Gui function to run
    window_title="Hello Image Heatmap",  # the window title
    window_size_auto=True,  # Auto size the application window given its widgets
    # Uncomment the next line to restore window position and size from previous run
    # window_restore_previous_geometry==True
    with_implot=True
)
```

and the result:
image

### CODE REVIEW

**Comment by pthom** [comment]
First, many thanks for your propositions, help is always very much appreciated ;-)

You are right, the bindings for add_colormap were not working properly. However, i think some adaptations are needed on your PR, in order to make its use easy to understand for the final user. 


In order to make it easier to express what I mean, I forked your branch and pushed two additional commits onto it:

https://github.com/pthom/imgui_bundle/commits/add_colormap_fix

* ad5392d720376d81e5fe3d3fd070b9666a870383 removes the automatic bindings for add_colormap which were broken (thanks for noting this!)
* 67cb292aa12b2c94ad79aec1d405740d22ac4c90 adds some doc for add_colormap in the stubs: this is always required when adding manual bindings. I added some doc for the users that describe the API we should try to reach. Please read it,  especially the part on the numpy array shape and dtype.

You may want to merge those changes onto your branch.

Now, more details on what I think should be done next:


```cpp
    m.def("add_colormap",
        [](const char * name, const py::array & cols, int size, bool qual=true)
             // The parameter size is not needed, as it is equal to cols.shape[0]
        {
            const void * values_from_pyarray = cols.data();

            // 1. Check the shape of the array: it should be two dimensionnal, the number of rows should be >  1 and the number of cols should be 4
           // if not, throw an exception with a nice message for the user

            // 2. check that cols.dtype is either float or uint32
           // if not, throw an exception with a nice message for the user


          // 3. Then call the correct version of AddColormap (i.e. the one that uses ImVec4 or ImU32)
            return ImPlot::AddColormap(name, static_cast<const uint32_t *>(values_from_pyarray),size, qual);

        }, py::arg("name"), py::arg("cols"), py::arg("size"), py::arg("qual") = true,
        "Add a new colormap."
        );
```

And then, may be the user demo should be also impacted inside [demos_python/demo_implot.py](https://github.com/pthom/imgui_bundle/blob/main/bindings/imgui_bundle/demos_python/demo_implot.py#L92)

I know this is a bit tedious, but it is needed if we want to keep a high quality and ease of use for the end user :-)

Would you be willing to work on these changes?

---

PS: one quick advice when using markdown on github. Use three backticks + a language name when pasting multiline code snippets (single backticks only work for inline code snippets). I already modified your message by adding those bacticks.

Example:

\`\`\`cpp
void foo();
\`\`\`

Will be shown as:

```cpp
void foo();
```

---

Thanks again!

**Comment by nick-0** [comment]
K, I made some changes, let me know what you think.
BTW, the function takes either a 1D array of uint32's or a 2D (Nx4-> RGBA) array of floats.

**Comment by pthom** [comment]
Ok, I just pushed 4 commits in here: https://github.com/pthom/imgui_bundle/commits/add_colormap_fix

https://github.com/pthom/imgui_bundle/commit/9661914ceed78fe4befaa918eb176ae14a42d523 adds cross platform utilities to test array types.

https://github.com/pthom/imgui_bundle/commit/34ae28bc0953f3cc0a8550d7be2aa0d778c72cb6 uses it to check for uint32

https://github.com/pthom/imgui_bundle/commit/ab616959c4cf18a6af1af3e2dbda912bea4c7c4d checks the number of columns

https://github.com/pthom/imgui_bundle/commit/77620ae16beedea075eb6d1d3a0f29727fd669e0 updates the doc

I did not test those. Could you run a test with both UIntu32 and float, and confirm that the bindings work?

Thanks!

**Comment by pthom** [comment]
>  did not test those. Could you run a test with both UIntu32 and float, and confirm that the bindings work?

update: I did some tests, and everything seems ok, so I merged the PR. Thanks!

**Pull request merged**
